[package]
name = "dec_25"
version = "0.1.0"
authors = ["Mathijs de Langen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
